name: Deploy to Production

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Dockerfile
        run: cat Dockerfile

      - name: List files
        run: ls -la

      - name: Check pm2 status
        run: pm2 status
