name: Deploy to Production

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Dockerfile
        run: cat Dockerfile

      - name: List files
        run: ls -la
